version = 0.1
[default.deploy.parameters]
stack_name = "localstack-opensearch-search-application-tutorial"
resolve_s3 = true
s3_prefix = "localstack-opensearch-search-application-tutorial"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
